### ISSUE TITLE
Please Upgrade to 2.2.3.Final

### ISSUE THREAD

**Issue by Gourav2912** [Apicurio/apicurio-registry-schema-validation#11]
Please Upgrade to 2.2.3.Final,  validateByArtifactReference() method with 2.2.2.Final  is not working correctly as it missing code to get list of artifactRefrences register at the time of artifact creation.

**Comment by carlesarnal** [comment]
Updated in master, note that this library will not validate the schema against any nested reference (for now), only against the main schema.
